### ISSUE TITLE
Zome call signing not working under WSL2

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/hc-spin#3]
I'm getting this log when running on WSL2 (Ubuntu 22.04), with `@holochain/hc-spin@^0.200.10`

```
[1] [63115:0225/173722.201353:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/user/1000/bus: No such file or directory
[1] [63115:0225/173722.201426:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/user/1000/bus: No such file or directory
[1] [63115:0225/173722.201455:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/user/1000/bus: No such file or directory
[1] [63115:0225/173722.201495:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/user/1000/bus: No such file or directory
[1] [hc-spin] | [hc run-local-services]: # HC BOOTSTRAP - ADDR: http://127.0.0.1:34475
[1] [hc-spin] | [hc run-local-services]: # HC BOOTSTRAP - RUNNING
[1] [hc-spin] | [hc run-local-services]: # HC SIGNAL - ADDR: ws://127.0.0.1:38557
[1] [hc-spin] | [hc run-local-services]: # HC SIGNAL - RUNNING
[1] [hc-spin] | [hc sandbox]: hc-sandbox: Creating 2 conductor sandboxes with same settings
[1] [hc-spin] | [hc sandbox]: 
[1] [hc-spin] | [hc sandbox]: # lair-keystore init generating secure config...
[1] [hc-spin] | [hc sandbox]: 
[1] [hc-spin] | [hc sandbox]: # lair-keystore init config:
[1] [hc-spin] | [hc sandbox]: "/tmp/nix-shell.cphyL4/IrA0AHSXnoSU-zES6ij6G/ks/lair-keystore-config.yaml"
[1] [hc-spin] | [hc sandbox]: 
[1] [hc-spin] | [hc sandbox]: # lair-keystore init connection_url:
[1] [hc-spin] | [hc sandbox]: unix:///tmp/nix-shell.cphyL4/IrA0AHSXnoSU-zES6ij6G/ks/socket?k=eFFlT1Kp1Tei07QsyGpWFwBouQI0-ATd2rmAvcvLylA
[1] [hc-spin] | [hc sandbox]: hc-sandbox: Config ConductorConfig { tracing_override: None, data_root_path: Some(DataRootPath("/tmp/nix-shell.cphyL4/IrA0AHSXnoSU-zES6ij6G")), keystore: LairServer { connection_url: Url2 { url: "unix:///tmp/nix-shell.cphyL4/IrA0AHSXnoSU-zES6ij6G/ks/socket?k=eFFlT1Kp1Tei07QsyGpWFwBouQI0-ATd2rmAvcvLylA" } }, dpki: None, admin_interfaces: Some([AdminInterfaceConfig { driver: Websocket { port: 0 } }]), network: KitsuneP2pConfig { transport_pool: [WebRTC { signal_url: "ws://127.0.0.1:38557" }], bootstrap_service: Some(Url2 { url: "http://127.0.0.1:34475/" }), tuning_params: KitsuneP2pTuningParams { gossip_strategy: "sharded-gossip", gossip_loop_iteration_delay_ms: 1000, gossip_outbound_target_mbps: 100.0, gossip_inbound_target_mbps: 100.0, gossip_historic_outbound_target_mbps: 100.0, gossip_historic_inbound_target_mbps: 100.0, gossip_burst_ratio: 100.0, gossip_peer_on_success_next_gossip_delay_ms: 60000, gossip_peer_on_error_next_gossip_delay_ms: 300000, gossip_agent_info_update_interval_ms: 300000, gossip_round_timeout_ms: 60000, gossip_redundancy_target: 100.0, gossip_max_batch_size: 1000000, gossip_dynamic_arcs: true, gossip_arc_clamping: "none", default_rpc_single_timeout_ms: 60000, default_rpc_multi_remote_agent_count: 3, default_rpc_multi_remote_request_grace_ms: 3000, agent_info_expires_after_ms: 1200000, tls_in_mem_session_storage: 512, proxy_keepalive_ms: 120000, proxy_to_expire_ms: 300000, concurrent_limit_per_thread: 4096, tx2_quic_max_idle_timeout_ms: 60000, tx2_pool_max_connection_count: 4096, tx2_channel_count_per_connection: 2, tx2_implicit_timeout_ms: 60000, tx2_initial_connect_retry_delay_ms: 200, tx5_connection_count_max: 4096, tx5_send_buffer_bytes_max: 65536, tx5_recv_buffer_bytes_max: 65536, tx5_incoming_message_bytes_max: 536870912, tx5_message_size_max: 16777216, tx5_internal_event_channel_size: 1024, tx5_timeout_s: 60, tx5_backoff_start_s: 5, tx5_backoff_max_s: 60, tx5_ban_time_s: 10, tx5_min_ephemeral_udp_port: 1, tx5_max_ephemeral_udp_port: 65535, danger_tls_keylog: "no_keylog", danger_gossip_recent_threshold_secs: 900, disable_publish: false, disable_recent_gossip: false, disable_historical_gossip: false, bootstrap_check_delay_backoff_multiplier: 2, bootstrap_max_delay_s: 300 }, network_type: QuicBootstrap, tracing_scope: None }, db_sync_strategy: Fast, tuning_params: None }
[1] [hc-spin] | [hc sandbox]: hc-sandbox: Created directory at: /tmp/nix-shell.cphyL4/IrA0AHSXnoSU-zES6ij6G Keep this path to rerun the same sandbox. It has also been saved to a file called `.hc` in your current working directory.
[1] [hc-spin] | [hc sandbox]: hc-sandbox: Created config at /tmp/nix-shell.cphyL4/IrA0AHSXnoSU-zES6ij6G/conductor-config.yaml
[1] [hc-spin] | [hc sandbox]: hc-sandbox: Command { std: "lair-keystore" "--lair-root" "/tmp/nix-shell.cphyL4/IrA0AHSXnoSU-zES6ij6G/ks" "server" "--piped", kill_on_drop: true }
[1] [hc-spin] | [hc sandbox]: # lair-keystore connection_url # unix:///tmp/nix-shell.cphyL4/IrA0AHSXnoSU-zES6ij6G/ks/socket?k=eFFlT1Kp1Tei07QsyGpWFwBouQI0-ATd2rmAvcvLylA #
[1] [hc-spin] | [hc sandbox]: # lair-keystore running #
[1] [hc-spin] | [hc sandbox]: 
[1] [hc-spin] | [hc sandbox]: Conductor ready.
[1] [hc-spin] | [hc sandbox]: 
[1] [hc-spin] | [hc sandbox]: # lair-keystore init generating secure config...
[1] [hc-spin] | [hc sandbox]: 
[1] [hc-spin] | [hc sandbox]: # lair-keystore init config:
[1] [hc-spin] | [hc sandbox]: "/tmp/nix-shell.cphyL4/dI7H-oyM9b4QqAEdeQzJF/ks/lair-keystore-config.yaml"
[1] [hc-spin] | [hc sandbox]: 
[1] [hc-spin] | [hc sandbox]: # lair-keystore init connection_url:
[1] [hc-spin] | [hc sandbox]: unix:///tmp/nix-shell.cphyL4/dI7H-oyM9b4QqAEdeQzJF/ks/socket?k=U_cXTJZh0WnFTR-7aOrtXLRm3UBj3WioD8e9U5VmsCo
[1] [hc-spin] | [hc sandbox]: hc-sandbox: Config ConductorConfig { tracing_override: None, data_root_path: Some(DataRootPath("/tmp/nix-shell.cphyL4/dI7H-oyM9b4QqAEdeQzJF")), keystore: LairServer { connection_url: Url2 { url: "unix:///tmp/nix-shell.cphyL4/dI7H-oyM9b4QqAEdeQzJF/ks/socket?k=U_cXTJZh0WnFTR-7aOrtXLRm3UBj3WioD8e9U5VmsCo" } }, dpki: None, admin_interfaces: Some([AdminInterfaceConfig { driver: Websocket { port: 0 } }]), network: KitsuneP2pConfig { transport_pool: [WebRTC { signal_url: "ws://127.0.0.1:38557" }], bootstrap_service: Some(Url2 { url: "http://127.0.0.1:34475/" }), tuning_params: KitsuneP2pTuningParams { gossip_strategy: "sharded-gossip", gossip_loop_iteration_delay_ms: 1000, gossip_outbound_target_mbps: 100.0, gossip_inbound_target_mbps: 100.0, gossip_historic_outbound_target_mbps: 100.0, gossip_historic_inbound_target_mbps: 100.0, gossip_burst_ratio: 100.0, gossip_peer_on_success_next_gossip_delay_ms: 60000, gossip_peer_on_error_next_gossip_delay_ms: 300000, gossip_agent_info_update_interval_ms: 300000, gossip_round_timeout_ms: 60000, gossip_redundancy_target: 100.0, gossip_max_batch_size: 1000000, gossip_dynamic_arcs: true, gossip_arc_clamping: "none", default_rpc_single_timeout_ms: 60000, default_rpc_multi_remote_agent_count: 3, default_rpc_multi_remote_request_grace_ms: 3000, agent_info_expires_after_ms: 1200000, tls_in_mem_session_storage: 512, proxy_keepalive_ms: 120000, proxy_to_expire_ms: 300000, concurrent_limit_per_thread: 4096, tx2_quic_max_idle_timeout_ms: 60000, tx2_pool_max_connection_count: 4096, tx2_channel_count_per_connection: 2, tx2_implicit_timeout_ms: 60000, tx2_initial_connect_retry_delay_ms: 200, tx5_connection_count_max: 4096, tx5_send_buffer_bytes_max: 65536, tx5_recv_buffer_bytes_max: 65536, tx5_incoming_message_bytes_max: 536870912, tx5_message_size_max: 16777216, tx5_internal_event_channel_size: 1024, tx5_timeout_s: 60, tx5_backoff_start_s: 5, tx5_backoff_max_s: 60, tx5_ban_time_s: 10, tx5_min_ephemeral_udp_port: 1, tx5_max_ephemeral_udp_port: 65535, danger_tls_keylog: "no_keylog", danger_gossip_recent_threshold_secs: 900, disable_publish: false, disable_recent_gossip: false, disable_historical_gossip: false, bootstrap_check_delay_backoff_multiplier: 2, bootstrap_max_delay_s: 300 }, network_type: QuicBootstrap, tracing_scope: None }, db_sync_strategy: Fast, tuning_params: None }
[1] [hc-spin] | [hc sandbox]: hc-sandbox: Created directory at: /tmp/nix-shell.cphyL4/dI7H-oyM9b4QqAEdeQzJF Keep this path to rerun the same sandbox. It has also been saved to a file called `.hc` in your current working directory.
[1] [hc-spin] | [hc sandbox]: hc-sandbox: Created config at /tmp/nix-shell.cphyL4/dI7H-oyM9b4QqAEdeQzJF/conductor-config.yaml
[1] [hc-spin] | [hc sandbox]: hc-sandbox: Command { std: "lair-keystore" "--lair-root" "/tmp/nix-shell.cphyL4/dI7H-oyM9b4QqAEdeQzJF/ks" "server" "--piped", kill_on_drop: true }
[1] [hc-spin] | [hc sandbox]: # lair-keystore connection_url # unix:///tmp/nix-shell.cphyL4/dI7H-oyM9b4QqAEdeQzJF/ks/socket?k=U_cXTJZh0WnFTR-7aOrtXLRm3UBj3WioD8e9U5VmsCo #
[1] [hc-spin] | [hc sandbox]: # lair-keystore running #
[0] 
[0] [vue-tsc] Found 0 errors. Watching for file changes.
[1] [hc-spin] | [hc sandbox]: 
[1] [hc-spin] | [hc sandbox]: Conductor ready.
[1] [hc-spin] | [hc sandbox]: hc-sandbox: Created [ConfigRootPath("/tmp/nix-shell.cphyL4/IrA0AHSXnoSU-zES6ij6G"), ConfigRootPath("/tmp/nix-shell.cphyL4/dI7H-oyM9b4QqAEdeQzJF")]
[1] [hc-spin] | [hc sandbox]: hc-sandbox: Command { std: "lair-keystore" "--lair-root" "/tmp/nix-shell.cphyL4/IrA0AHSXnoSU-zES6ij6G/ks" "server" "--piped", kill_on_drop: true }
[1] [hc-spin] | [hc sandbox]: hc-sandbox: Command { std: "lair-keystore" "--lair-root" "/tmp/nix-shell.cphyL4/dI7H-oyM9b4QqAEdeQzJF/ks" "server" "--piped", kill_on_drop: true }
[1] [hc-spin] | [hc sandbox]: # lair-keystore connection_url # unix:///tmp/nix-shell.cphyL4/IrA0AHSXnoSU-zES6ij6G/ks/socket?k=eFFlT1Kp1Tei07QsyGpWFwBouQI0-ATd2rmAvcvLylA #
[1] [hc-spin] | [hc sandbox]: # lair-keystore running #
[1] [hc-spin] | [hc sandbox]: # lair-keystore connection_url # unix:///tmp/nix-shell.cphyL4/dI7H-oyM9b4QqAEdeQzJF/ks/socket?k=U_cXTJZh0WnFTR-7aOrtXLRm3UBj3WioD8e9U5VmsCo #
[1] [hc-spin] | [hc sandbox]: # lair-keystore running #
[1] [hc-spin] | [hc sandbox]: 
[1] [hc-spin] | [hc sandbox]: Conductor ready.
[1] [hc-spin] | [hc sandbox]: hc-sandbox: Conductor launched #!0 {"admin_port":39879,"app_ports":[36231]}
[1] [hc-spin] | [hc sandbox]: hc-sandbox: Connected successfully to a running holochain
[1] [hc-spin] | [hc sandbox]: 
[1] [hc-spin] | [hc sandbox]: Conductor ready.
[1] [hc-spin] | [hc sandbox]: hc-sandbox: Conductor launched #!1 {"admin_port":39369,"app_ports":[42617]}
[1] [hc-spin] | [hc sandbox]: hc-sandbox: Connected successfully to a running holochain
[1] [63115:0225/173735.940036:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/user/1000/bus: No such file or directory
[0] 
[0] 🌼   daisyUI 4.7.2
[0] ├─ ✔︎ 2 themes added         https://daisyui.com/docs/themes
[0] ╰─ ★ Star daisyUI on GitHub https://github.com/saadeghi/daisyui
[0] 
[1] Error occurred in handler for 'sign-zome-call': TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
[1]     at Function.from (<anonymous>)
[1]     at handleSignZomeCall (/home/thetasinner/source/hwot/node_modules/@holochain/hc-spin/dist/main/index.js:11857:47)
[1]     at WebContents.<anonymous> (node:electron/js2c/browser_init:2:77976)
[1]     at WebContents.emit (node:events:517:28)
[1] Error occurred in handler for 'sign-zome-call': TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
[1]     at Function.from (<anonymous>)
[1]     at handleSignZomeCall (/home/thetasinner/source/hwot/node_modules/@holochain/hc-spin/dist/main/index.js:11857:47)
[1]     at WebContents.<anonymous> (node:electron/js2c/browser_init:2:77976)
[1]     at WebContents.emit (node:events:517:28)
[1] [63115:0225/173738.189963:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/user/1000/bus: No such file or directory
[1] Error occurred in handler for 'sign-zome-call': TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
[1]     at Function.from (<anonymous>)
[1]     at handleSignZomeCall (/home/thetasinner/source/hwot/node_modules/@holochain/hc-spin/dist/main/index.js:11857:47)
[1]     at WebContents.<anonymous> (node:electron/js2c/browser_init:2:77976)
[1]     at WebContents.emit (node:events:517:28)
[1] Error occurred in handler for 'sign-zome-call': TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
[1]     at Function.from (<anonymous>)
[1]     at handleSignZomeCall (/home/thetasinner/source/hwot/node_modules/@holochain/hc-spin/dist/main/index.js:11857:47)
[1]     at WebContents.<anonymous> (node:electron/js2c/browser_init:2:77976)
[1]     at WebContents.emit (node:events:517:28)
[1] 
[1] (electron:63115): dconf-WARNING **: 17:37:47.590: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:37:47.615: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:37:47.633: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:37:47.646: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:37:47.662: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:37:47.679: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:37:47.695: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:37:47.714: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:37:47.732: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:37:47.748: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:37:47.765: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:37:47.783: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:37:47.800: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:37:47.817: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:37:47.834: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:37:47.850: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:37:47.868: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:37:48.802: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:37:48.803: failed to commit changes to dconf: Could not connect: No such file or directory
[1] Warning: vkCreateInstance: Found no drivers!
[1] Warning: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
[1]     at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:101)
[1]     at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:493)
[1]     at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:379)
[1]     at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:301)
[1]     at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:556)
[1] 
[1] Warning: EGL_EXT_create_context_robustness must be supported
[1]     at Create (../../third_party/dawn/src/dawn/native/opengl/ContextEGL.cpp:79)
[1]     at Create (../../third_party/dawn/src/dawn/native/opengl/PhysicalDeviceGL.cpp:110)
[1] 
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:32.852: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:32.879: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:32.903: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:32.914: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:32.930: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:32.949: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:32.966: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:32.984: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:33.001: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:33.018: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:33.035: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:33.052: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:33.068: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:33.086: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:33.102: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:33.119: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:33.136: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:34.370: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:34.389: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:34.402: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:34.416: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:34.432: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:34.448: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:34.465: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:34.480: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:34.501: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:34.514: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:34.531: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:34.548: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:34.565: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:34.580: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:34.596: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:34.616: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:35.807: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:35.824: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:35.841: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:36.029: failed to commit changes to dconf: Could not connect: No such file or directory
[1] 
[1] (electron:63115): dconf-WARNING **: 17:39:36.029: failed to commit changes to dconf: Could not connect: No such file or directory
[1] Error occurred in handler for 'sign-zome-call': TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
[1]     at Function.from (<anonymous>)
[1]     at handleSignZomeCall (/home/thetasinner/source/hwot/node_modules/@holochain/hc-spin/dist/main/index.js:11857:47)
[1]     at WebContents.<anonymous> (node:electron/js2c/browser_init:2:77976)
[1]     at WebContents.emit (node:events:517:28)
```

**Comment by matthme** [comment]
I'm surprised that this error can occur without throwing a runtime error before it even reaches that line. I have to improve error handling.
Does this error occur consistently each time you run `hc-spin` in that environemt?

**Comment by ThetaSinner** [comment]
Unfortunately yes it does. This is happening in both my environments, one on my work machine that I've had for a while so I don't think it's related to any recent changes I've made in there. The other is on my personal machine and is brand new because I was having other WSL issues.

I'm not really sure what's going on here. It could be something wrong with my environments but if you know where this errors happens and could get it to give some more context about what went wrong I'd be happy to run it again and get you some more information about what's happening for me :)

**Comment by matthme** [comment]
Okay, some context is that this error occurs if `windowInfo.agentPubKey` is not defined on [this](https://github.com/holochain/hc-spin/blob/b78b9c8ab04b773cb9dc5f1402729bd66fbe6d71/src/main/index.ts#L123) line. However `windowInfo` itself must be defined because otherwise the error would be
```
TypeError: Cannot read properties of undefined (reading 'agentPubKey')
```
The `agentPubKey` property is set on [this](https://github.com/holochain/hc-spin/blob/b78b9c8ab04b773cb9dc5f1402729bd66fbe6d71/src/main/index.ts#L342) line based on what has been returned by appInfo. This could be undefined then if `appInfo` returned `null` (which it apparently [can](https://github.com/holochain/holochain-client-js/issues/232)). However, if that was the case, then I would already expect an error on that line 342 like (I tried that locally)
```
TypeError: Cannot read properties of null (reading 'agent_pub_key')
```
So I'm just confused how that can even happen. Can you try to run hc-spin by explicitly setting the app-id via the `--app-id` argument to see whether it might in your case use a wrong app id for which appInfo returns null?

And another question: Did you try to run the same project in a non-WSL2 environment yet?

**Comment by ThetaSinner** [comment]
Ahh okay, thank you for pointing me at the right code. That helped me debug my mistake, the message I'm getting back from the `appInfo` call is:

```
[1] Got app info: {"type":{"deserialization":null},"data":"Bytes(Deserialize(\"wrong msgpack marker FixStr(8)\"))"}
```

I'd expect the JS client to have errored that response though... because the the response type clearly doesn't match the request type. Maybe a bug there?

But the problem is me working on weekly Holochain but using 0.200.10 of `hc-spin`. I've switched to `0.300.2` and it works just fine.

> Did you try to run the same project in a non-WSL2 environment yet?

I haven't, just my WSL environments, but as it turns out WSL isn't messing me up, I am messing me up :)

**Comment by matthme** [comment]
Ah great! I'll leave this issue open nevertheless until I added proper error handling for the `null` case.

**Comment by matthme** [comment]
AppInfo being null is being handled with an [error] now.
